feat(37): create materials list in classroom dashboard
tareq-mahmood-sazim/superteacher-frontend pull request #17
Opened 2024-11-10 16:58 UTC by tareq-mahmood-sazim

## Description of Change

- this container component will be inside classroom dashboard
- will contain components for teacher dashboard to update materials
- it will enlist all the materials provided by teacher in the classroom

### Please list which modules are affected by your changes

modules/classroom/components/classroom/createMaterials/CreateMaterials.tsx, modules/classroom/containers/classroomContainer/ClassroomContainer.tsx, modules/classroom/containers/materialsContainer/MaterialContainer.tsx, modules/dashboard/teacher/containers/TeachersContainer.tsx, modules/dashboard/student/containers/studentContainer/StudentContainer.tsx

---

- [x] **You assure that you have tested the modules properly and there are no breaking changes**
- [x] **You adhere to Sazim's [Engineering Principles](https://docs.google.com/document/d/10mowIwsuYMyNkXS7aeL7AJyVNMYVh1vdMf7yn-A6I1k/edit#heading=h.qqetrc8w2lm8)**

## Associated Ticket Link(s)

- https://trello.com/c/4D8pbTXk

## Related Pull Request(s)

- none

## Screenshots / Screen Recordings

2024-11-14 12:24 UTC, ishmamur-rahman-sazim requested changes

2024-11-14 12:24 UTC, ishmamur-rahman-sazim commented on modules/classroom/components/classroom/createMaterials/CreateMaterials.tsx
> +  const [appear, setAppear] = useState<boolean>(true);
[NITPICK] A more descriptive name would be `areButtonsVisible`.
[Here's a reference on naming boolean variables](https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig)

2024-11-14 12:24 UTC, ishmamur-rahman-sazim commented on modules/classroom/components/classroom/createMaterials/addAssignment/AddAssignment.tsx
> +};
Import types from a `.types.ts` file

2024-11-14 12:24 UTC, ishmamur-rahman-sazim commented on modules/classroom/components/classroom/createMaterials/addAssignment/AddAssignment.tsx
> +  const fileProcessing = async (data: FormValues): Promise<string[]> => {
Function names should be a verb/verb phrase as per conventions. Suggested name - `processFiles`

2024-11-18 06:19 UTC, tareq-mahmood-sazim commented on modules/classroom/containers/materialsContainer/MaterialContainer.tsx
yes bhaia we do since it will hold a lot of components

2024-11-18 06:23 UTC, tareq-mahmood-sazim commented on modules/classroom/components/classroom/createMaterials/addAssignment/AddAssignment.tsx
> +      // Todo -> throw error notification here
they will be made in the next PR bhaia

2024-11-29 12:35 UTC, merged