feat(St-21): added auth based state management
tareq-mahmood-sazim/superteacher-frontend pull request #2
Opened 2024-10-15 09:06 UTC by tareq-mahmood-sazim

## Description of Change

- Refactored according to conventional structure of frontend
- Replaced mantine validations with zod validations
- Added auth based state management using reducers
- Added types
- Added rtk queries for successful authentication
- Added navbar to preview state changing

### Please list which modules are affected by your changes

@/modules/** ,@/redux/reducers/*, @redux/rtk-apis/users, @typedefs/*

---

- [x] **You assure that you have tested the modules properly and there are no breaking changes**
- [x] **You adhere to Sazim's [Engineering Principles](https://docs.google.com/document/d/10mowIwsuYMyNkXS7aeL7AJyVNMYVh1vdMf7yn-A6I1k/edit#heading=h.qqetrc8w2lm8)**

## Associated Ticket Link(s)

- https://trello.com/c/VOo3O01Z

## Related Pull Request(s)

-

## Screenshots / Screen Recordings

2024-10-15 22:10 UTC, ishmamur-rahman-sazim requested changes

2024-10-15 22:10 UTC, ishmamur-rahman-sazim commented on shared/typedefs/interfaces.ts
As per conventions, interface names are generally prefixed with `I`

2024-10-15 22:10 UTC, ishmamur-rahman-sazim commented on shared/redux/rtk-apis/profiles/profiles.types.ts
We can remove this empty file.

2024-10-15 22:10 UTC, ishmamur-rahman-sazim commented on shared/components/Navbar/components/profileDropdown/profileDropdownButton.tsx
> +
Can we destructure the preceding lines? 
`const { email, userId, claim } = useSelector((state: TRootState) => state.authenticatedUser);`

2024-10-15 22:10 UTC, ishmamur-rahman-sazim commented on shared/components/Navbar/components/createClass/components/createClassForm.tsx
> +          data={[
[NITPICK] We can have this as an imported constant.

2024-10-16 11:01 UTC, tareq-mahmood-sazim commented on shared/typedefs/interfaces.ts
All changes have been brought on #3

2024-10-21 10:42 UTC, ishmamur-rahman-sazim approved these changes

2024-10-28 09:44 UTC, merged