feat(ST-43): adding, removing participants in classroom added with endpoint refactoring
tareq-mahmood-sazim/superteacher-frontend pull request #24
Opened 2024-11-19 10:07 UTC by tareq-mahmood-sazim

## Description of Change

- created modal components to add, remove, view informations of the participants.
- modified previously written rtk queries for usage integration
- refactored some endpoints for better usage advantage to integrate backend and frontend

- [x] **You assure that you have tested the modules properly and there are no breaking changes**
- [x] **You adhere to Sazim's [Engineering Principles](https://docs.google.com/document/d/10mowIwsuYMyNkXS7aeL7AJyVNMYVh1vdMf7yn-A6I1k/edit#heading=h.qqetrc8w2lm8)**

## Associated Ticket Link(s)

- https://trello.com/c/C08gb4V9

## Related Pull Request(s)

-

## Screenshots / Screen Recordings

2024-11-20 08:17 UTC, ishmamur-rahman-sazim requested changes

2024-11-20 08:17 UTC, ishmamur-rahman-sazim commented on pages/dashboard/home.page.tsx
> +    }, 4000);
[JC] Why are we reloading here?

2024-11-20 08:17 UTC, ishmamur-rahman-sazim commented on modules/classroom/containers/peopleContainer/PeopleContainer.tsx
> +    return <div>Both owner and participants required to render this component</div>;
[JC] Would it be possible to see this page if there are no owner (teacher) of a classroom?

2024-11-20 08:17 UTC, ishmamur-rahman-sazim commented on modules/classroom/components/peopleDetail/PeopleDetail.tsx
> +      // router.reload();
Remove comment

2024-11-20 08:17 UTC, ishmamur-rahman-sazim commented on modules/classroom/components/addStudentOnClassroomForm/AddStudentOnClassForm.tsx
> +      console.log(addedOnClassroom);
Remove console statements

2024-11-20 08:17 UTC, ishmamur-rahman-sazim commented on modules/classroom/components/addStudentOnClassroomForm/AddStudentOnClassForm.tsx
>  }
Let's move this Interface to a separate file and follow the naming convention

2024-11-25 08:45 UTC, tareq-mahmood-sazim commented on modules/classroom/containers/peopleContainer/PeopleContainer.tsx
> +    return <div>Both owner and participants required to render this component</div>;
if there are no owner, then this classroom cannot be created, if a teacher is removed, a classroom is removed with the teacher since classrooms are dependent on user-profiles bhaia.

2024-11-25 10:21 UTC, ishmamur-rahman-sazim commented on modules/classroom/containers/peopleContainer/PeopleContainer.tsx
> +    return <div>Both owner and participants required to render this component</div>;
So this is never going to render? Why do we have the logic for this then :thinking:

2024-11-25 10:22 UTC, ishmamur-rahman-sazim approved these changes

2024-11-25 11:03 UTC, tareq-mahmood-sazim commented on modules/classroom/containers/peopleContainer/PeopleContainer.tsx
> +    return <div>Both owner and participants required to render this component</div>;
If this logic is not present, the all paths in of the function does not faces a return point bhaia.

2024-11-26 09:28 UTC, merged